disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Jason Dai"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Jason Dai's profile"

["params.author"]
name = "Jason Dai"
headline = ""
image = "Jason Dai-thermofisher (face square).jpg"
bio = "I am a bioinformatics scientist, software developer, and data scientist passionate about leveraging AI and advanced computing to create innovative solutions across bioinformatics and fintech domains."
