disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Jason Dai"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = "Jason Dai's profile"

["params.author"]
name = "Jason Dai"
headline = ""
