[[main]]
none = "none"

[[main]]
name = "Background"
pageRef = "background_page"
identifier = "xaO6otvm0d"
weight = 2

[[main]]
name = "Home"
pageRef = "home_page"
identifier = "rcBfg1tgSs"
weight = 1

[[main]]
name = "Experience"
pageRef = "experience_page"
identifier = "4vpp11z6PV"
weight = 3

[[main]]
name = "Projects"
pageRef = "projects_page"
identifier = "LYFWxTDyvs"
weight = 4

[[main]]
name = "Contact"
pageRef = "contact_page"
identifier = "rezxHgyr5M"
weight = 9_999

[[footer]]
none = "none"
